import { useEffect, useMemo, useRef, useState } from "react";
import { Field } from "../../../components/ui/Field";
import { Modal } from "../../../components/ui/Modal";
import { SearchableSelect } from "../../../components/ui/SearchableSelect";
import { productsApi, type SupplierPriceHistoryPage, type SupplierPriceSummary } from "../api/productsApi";

type Option = { value: string | number; label: string; code?: string };
type ProductUnit = { productUnitId?: number; unitId: string; isPurchaseUnit: boolean; isActive: boolean };
type Link = { productSupplierId?: number; supplierId: string; isPrimarySupplier: boolean; isActive: boolean };
type SupplierUnit = { productSupplierUnitId?: number; productSupplierId: number; productUnitId: number; supplierProductCode: string; minimumOrderQty: string; leadTimeDays: string; isDefaultPurchaseUnit: boolean; isActive: boolean };
type Draft = { id: string; action: "ADD_INITIAL_PRICE" | "CHANGE_PRICE" | "END_PRICE" | "CANCEL_FUTURE_PRICE"; productSupplierPriceId?: number; productSupplierUnitId: number; supplierLabel: string; unitLabel: string; currentPrice?: string; price?: number; currencyCode: string; effectiveMode?: "NOW" | "SCHEDULED"; effectiveFrom?: string; effectiveTo?: string | null };
type PriceEditor = { kind: "ADD" | "CHANGE" | "END"; group?: SupplierPriceSummary; draftIndex?: number };

const json = (value: unknown) => JSON.stringify(value);
const money = (currency: string, value: string | number) => `${currency || "LKR"} ${Number(value || 0).toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
const dateTime = (value?: string | null) => value ? new Intl.DateTimeFormat(undefined, { day: "2-digit", month: "2-digit", year: "numeric", hour: "2-digit", minute: "2-digit" }).format(new Date(value)) : "—";
const localInput = (date: Date) => new Date(date.getTime() - date.getTimezoneOffset() * 60000).toISOString().slice(0, 16);

export function ProductSupplierPricesUpdate({ productId, productUnits, supplierOptions, unitOptions, unitsDirty }: { productId: number; productUnits: ProductUnit[]; supplierOptions: Option[]; unitOptions: Option[]; unitsDirty: boolean }) {
  const [links, setLinks] = useState<Link[]>([]), [savedLinks, setSavedLinks] = useState<Link[]>([]);
  const [supplierUnits, setSupplierUnits] = useState<SupplierUnit[]>([]), [savedUnits, setSavedUnits] = useState<SupplierUnit[]>([]);
  const [summary, setSummary] = useState<SupplierPriceSummary[]>([]), [drafts, setDrafts] = useState<Draft[]>([]);
  const [linkEditor, setLinkEditor] = useState<number | "new" | null>(null), [unitEditor, setUnitEditor] = useState<number | "new" | null>(null);
  const [linkForm, setLinkForm] = useState<Link>({ supplierId: "", isPrimarySupplier: false, isActive: true });
  const [unitForm, setUnitForm] = useState<SupplierUnit>({ productSupplierId: 0, productUnitId: 0, supplierProductCode: "", minimumOrderQty: "1", leadTimeDays: "", isDefaultPurchaseUnit: false, isActive: true });
  const [priceEditor, setPriceEditor] = useState<PriceEditor | null>(null);
  const [priceForm, setPriceForm] = useState({ supplierId: "", productSupplierUnitId: "", price: "", effectiveMode: "NOW", effectiveFrom: "", effectiveTo: "" });
  const [publishOpen, setPublishOpen] = useState(false), [historyOpen, setHistoryOpen] = useState(false);
  const [history, setHistory] = useState<SupplierPriceHistoryPage | null>(null);
  const [filters, setFilters] = useState({ page: 1, supplierId: "", productSupplierUnitId: "", status: "", fromDate: "", toDate: "" });
  const [busy, setBusy] = useState(false), [error, setError] = useState(""), [success, setSuccess] = useState("");
  const priorUnitsDirty = useRef(unitsDirty);

  const purchaseUnits = useMemo(() => productUnits.filter((row) => row.productUnitId && row.isActive && row.isPurchaseUnit).map((row) => ({ value: row.productUnitId!, label: unitOptions.find((option) => String(option.value) === row.unitId)?.label ?? "Purchase unit" })), [productUnits, unitOptions]);
  const linksDirty = json(links) !== json(savedLinks), supplierUnitsDirty = json(supplierUnits) !== json(savedUnits);
  const activeLinks = links.filter((row) => row.isActive && row.productSupplierId);
  const linkById = (id: number) => links.find((row) => Number(row.productSupplierId) === id);
  const supplierName = (id: string | number) => supplierOptions.find((row) => String(row.value) === String(id))?.label?.replace(/\s*\([^)]*\)$/, "") ?? "Supplier";
  const unitName = (id: string | number) => purchaseUnits.find((row) => String(row.value) === String(id))?.label ?? "Purchase unit";
  const activeSupplierUnits = supplierUnits.filter((row) => row.isActive && activeLinks.some((link) => Number(link.productSupplierId) === row.productSupplierId));
  const tomorrow = () => { const value = new Date(); value.setDate(value.getDate() + 1); return localInput(value); };

  const refresh = async () => {
    setBusy(true); setError("");
    try {
      const [product, units, prices] = await Promise.all([productsApi.get(productId), productsApi.productSupplierUnits(), productsApi.supplierPriceSummary(productId)]);
      const nextLinks: Link[] = (product.productSuppliers ?? []).map((row: any) => ({ productSupplierId: Number(row.productSupplierId), supplierId: String(row.supplierId), isPrimarySupplier: Boolean(row.isPrimarySupplier), isActive: row.isActive !== false }));
      const ids = new Set(nextLinks.map((row) => Number(row.productSupplierId)));
      const nextUnits: SupplierUnit[] = units.filter((row: any) => ids.has(Number(row.productSupplierId))).map((row: any) => ({ productSupplierUnitId: Number(row.productSupplierUnitId), productSupplierId: Number(row.productSupplierId), productUnitId: Number(row.productUnitId), supplierProductCode: row.supplierProductCode ?? "", minimumOrderQty: row.minimumOrderQty == null ? "" : String(row.minimumOrderQty), leadTimeDays: row.leadTimeDays == null ? "" : String(row.leadTimeDays), isDefaultPurchaseUnit: Boolean(row.isDefaultPurchaseUnit), isActive: row.isActive !== false }));
      setLinks(nextLinks); setSavedLinks(nextLinks); setSupplierUnits(nextUnits); setSavedUnits(nextUnits); setSummary(prices);
    } catch (reason) { setError((reason as Error).message); } finally { setBusy(false); }
  };
  useEffect(() => { void refresh(); }, [productId]);
  useEffect(() => { if (priorUnitsDirty.current && !unitsDirty) void refresh(); priorUnitsDirty.current = unitsDirty; }, [unitsDirty]);
  useEffect(() => { if (!historyOpen) return; let active = true; setBusy(true); productsApi.supplierPriceHistory(productId, { ...filters, limit: 25 }).then((value) => active && setHistory(value)).catch((reason) => active && setError((reason as Error).message)).finally(() => active && setBusy(false)); return () => { active = false; }; }, [historyOpen, productId, filters]);

  const openLink = (index?: number) => { setLinkForm(index == null ? { supplierId: "", isPrimarySupplier: false, isActive: true } : { ...links[index] }); setLinkEditor(index == null ? "new" : index); };
  const keepLink = () => {
    if (!linkForm.supplierId) return setError("Supplier is required.");
    if (links.some((row, index) => index !== linkEditor && row.supplierId === linkForm.supplierId && row.isActive)) return setError("This supplier is already linked to the product.");
    let next = linkEditor === "new" ? [...links, linkForm] : links.map((row, index) => index === linkEditor ? linkForm : row);
    if (linkForm.isPrimarySupplier) next = next.map((row, index) => ({ ...row, isPrimarySupplier: linkEditor === "new" ? index === next.length - 1 : index === linkEditor }));
    setLinks(next); setLinkEditor(null); setError("");
  };
  const saveLinks = async () => { setBusy(true); setError(""); try { await productsApi.updateSuppliers(productId, links.map((row) => ({ productSupplierId: row.productSupplierId, supplierId: Number(row.supplierId), isPrimarySupplier: row.isPrimarySupplier, isActive: row.isActive }))); await refresh(); setSuccess("Supplier changes saved."); } catch (reason) { setError((reason as Error).message); } finally { setBusy(false); } };

  const openUnit = (index?: number) => { setUnitForm(index == null ? { productSupplierId: Number(activeLinks[0]?.productSupplierId ?? 0), productUnitId: Number(purchaseUnits[0]?.value ?? 0), supplierProductCode: "", minimumOrderQty: "1", leadTimeDays: "", isDefaultPurchaseUnit: false, isActive: true } : { ...supplierUnits[index] }); setUnitEditor(index == null ? "new" : index); };
  const keepUnit = () => {
    if (!unitForm.productSupplierId || !unitForm.productUnitId) return setError("Supplier and Purchase Unit are required.");
    if (supplierUnits.some((row, index) => index !== unitEditor && row.productSupplierId === unitForm.productSupplierId && row.productUnitId === unitForm.productUnitId)) return setError("This Supplier Purchase Unit already exists.");
    let next = unitEditor === "new" ? [...supplierUnits, unitForm] : supplierUnits.map((row, index) => index === unitEditor ? unitForm : row);
    const active = next.filter((row) => row.productSupplierId === unitForm.productSupplierId && row.isActive);
    if (unitForm.isDefaultPurchaseUnit || active.length === 1) next = next.map((row, index) => row.productSupplierId === unitForm.productSupplierId ? { ...row, isDefaultPurchaseUnit: row.isActive && (unitEditor === "new" ? index === next.length - 1 : index === unitEditor) } : row);
    setSupplierUnits(next); setUnitEditor(null); setError("");
  };
  const toggleUnit = (index: number) => setSupplierUnits((rows) => { let next = rows.map((row, i) => i === index ? { ...row, isActive: !row.isActive, isDefaultPurchaseUnit: row.isActive ? false : row.isDefaultPurchaseUnit } : row); const changed = next[index], active = next.filter((row) => row.productSupplierId === changed.productSupplierId && row.isActive); if (active.length && !active.some((row) => row.isDefaultPurchaseUnit)) next = next.map((row) => row === active[0] ? { ...row, isDefaultPurchaseUnit: true } : row); return next; });
  const saveSupplierUnits = async () => {
    setBusy(true); setError("");
    try {
      for (const row of supplierUnits) {
        const saved = savedUnits.find((item) => item.productSupplierUnitId === row.productSupplierUnitId);
        const data = { supplierProductCode: row.supplierProductCode.trim() || null, minimumOrderQty: row.minimumOrderQty ? Number(row.minimumOrderQty) : null, leadTimeDays: row.leadTimeDays ? Number(row.leadTimeDays) : null, isDefaultPurchaseUnit: row.isDefaultPurchaseUnit };
        if (!row.productSupplierUnitId) await productsApi.createProductSupplierUnit({ productSupplierId: row.productSupplierId, productUnitId: row.productUnitId, ...data });
        else { if (saved && json({ ...saved, isActive: undefined }) !== json({ ...row, isActive: undefined })) await productsApi.updateProductSupplierUnit(row.productSupplierUnitId, data); if (saved && saved.isActive !== row.isActive) await (row.isActive ? productsApi.activateProductSupplierUnit(row.productSupplierUnitId) : productsApi.deactivateProductSupplierUnit(row.productSupplierUnitId)); }
      }
      await refresh(); setSuccess("Supplier Purchase Units saved.");
    } catch (reason) { setError((reason as Error).message); } finally { setBusy(false); }
  };

  const openPrice = (kind: "ADD" | "CHANGE" | "END", group?: SupplierPriceSummary) => { const unit = group ? supplierUnits.find((row) => row.productSupplierUnitId === Number(group.productSupplierUnitId)) : activeSupplierUnits[0], link = unit ? linkById(unit.productSupplierId) : undefined; setPriceForm({ supplierId: link?.supplierId ?? "", productSupplierUnitId: String(unit?.productSupplierUnitId ?? ""), price: "", effectiveMode: "NOW", effectiveFrom: tomorrow(), effectiveTo: tomorrow() }); setPriceEditor({ kind, group }); };
  const saveDraft = () => {
    if (!priceEditor) return; const productSupplierUnitId = Number(priceForm.productSupplierUnitId);
    if (!productSupplierUnitId) return setError("Supplier Purchase Unit is required.");
    if (priceEditor.kind !== "END" && Number(priceForm.price) <= 0) return setError("Purchase price must be greater than zero.");
    if (drafts.some((row, index) => index !== priceEditor.draftIndex && row.productSupplierUnitId === productSupplierUnitId)) return setError("A draft already exists for this Supplier Purchase Unit.");
    const unit = supplierUnits.find((row) => row.productSupplierUnitId === productSupplierUnitId)!, link = linkById(unit.productSupplierId), group = priceEditor.group;
    const draft: Draft = { id: priceEditor.draftIndex == null ? crypto.randomUUID() : drafts[priceEditor.draftIndex].id, action: priceEditor.kind === "ADD" ? "ADD_INITIAL_PRICE" : priceEditor.kind === "CHANGE" ? "CHANGE_PRICE" : "END_PRICE", productSupplierPriceId: group?.current?.productSupplierPriceId, productSupplierUnitId, supplierLabel: supplierName(link?.supplierId ?? ""), unitLabel: unitName(unit.productUnitId), currentPrice: group?.current?.purchasePrice, price: priceEditor.kind === "END" ? undefined : Number(priceForm.price), currencyCode: group?.current?.currencyCode ?? "LKR", effectiveMode: priceForm.effectiveMode as "NOW" | "SCHEDULED", effectiveFrom: priceForm.effectiveMode === "SCHEDULED" && priceEditor.kind !== "END" ? new Date(priceForm.effectiveFrom).toISOString() : undefined, effectiveTo: priceEditor.kind === "END" && priceForm.effectiveMode === "SCHEDULED" ? new Date(priceForm.effectiveTo).toISOString() : null };
    setDrafts((rows) => priceEditor.draftIndex == null ? [...rows, draft] : rows.map((row, index) => index === priceEditor.draftIndex ? draft : row)); setPriceEditor(null); setError("");
  };
  const editDraft = (index: number) => { const draft = drafts[index], group = summary.find((row) => Number(row.productSupplierUnitId) === draft.productSupplierUnitId), unit = supplierUnits.find((row) => row.productSupplierUnitId === draft.productSupplierUnitId), link = unit ? linkById(unit.productSupplierId) : undefined; setPriceForm({ supplierId: link?.supplierId ?? "", productSupplierUnitId: String(draft.productSupplierUnitId), price: String(draft.price ?? ""), effectiveMode: draft.effectiveMode ?? "NOW", effectiveFrom: draft.effectiveFrom ? localInput(new Date(draft.effectiveFrom)) : tomorrow(), effectiveTo: draft.effectiveTo ? localInput(new Date(draft.effectiveTo)) : tomorrow() }); setPriceEditor({ kind: draft.action === "ADD_INITIAL_PRICE" ? "ADD" : draft.action === "CHANGE_PRICE" ? "CHANGE" : "END", group, draftIndex: index }); };
  const cancelFuture = (group: SupplierPriceSummary) => { const id = Number(group.productSupplierUnitId); if (drafts.some((row) => row.productSupplierUnitId === id)) return setError("A draft already exists for this Supplier Purchase Unit."); const unit = supplierUnits.find((row) => row.productSupplierUnitId === id), link = unit ? linkById(unit.productSupplierId) : undefined; setDrafts((rows) => [...rows, { id: crypto.randomUUID(), action: "CANCEL_FUTURE_PRICE", productSupplierPriceId: group.nextScheduled.productSupplierPriceId, productSupplierUnitId: id, supplierLabel: supplierName(link?.supplierId ?? ""), unitLabel: unitName(unit?.productUnitId ?? 0), currentPrice: group.nextScheduled.purchasePrice, currencyCode: group.nextScheduled.currencyCode }]); };
  const publish = async () => { setBusy(true); setError(""); try { const actions = drafts.map(({ id: _id, supplierLabel: _supplier, unitLabel: _unit, currentPrice: _current, currencyCode: _currency, ...action }) => ({ ...action, effectiveTo: action.effectiveTo || null })); setSummary(await productsApi.publishSupplierPrices(productId, actions)); setDrafts([]); setPublishOpen(false); setSuccess("Purchase prices published."); } catch (reason) { setError((reason as Error).message); } finally { setBusy(false); } };
  const blocked = unitsDirty || linksDirty || supplierUnitsDirty;

  return <div className="supplier-price-workspace">
    <div className="supplier-price-heading"><div><h2>Suppliers &amp; Purchase Prices</h2><p>Manage approved suppliers, their purchase units, and current or scheduled purchase costs.</p><strong>Supplier changes: {linksDirty ? 1 : 0} <span>•</span> Supplier Unit changes: {supplierUnitsDirty ? 1 : 0} <span>•</span> Unpublished price changes: {drafts.length}</strong></div><div className="supplier-price-header-actions"><button className="btn btn-secondary" onClick={() => setHistoryOpen(true)}>View Purchase Price History</button><button className="btn btn-primary" disabled={!drafts.length || blocked || busy} onClick={() => setPublishOpen(true)}>Publish Purchase Prices ({drafts.length})</button></div></div>
    {unitsDirty && <div className="warning-box">Save Product Unit changes before adding or publishing purchase price changes.</div>}{error && <div className="error-box">{error}</div>}{success && <div className="success-box">{success}</div>}
    <section className="supplier-price-panel"><h3>Approved Suppliers</h3><div className="supplier-price-table"><div className="supplier-price-row supplier-link-final-columns supplier-price-table-head"><span>Supplier</span><span>Supplier Code</span><span>Primary</span><span>Status</span><span>Actions</span></div>{links.map((row, index) => <div className="supplier-price-row supplier-link-final-columns" key={row.productSupplierId ?? `new-${index}`}><strong>{supplierName(row.supplierId)}</strong><span>{supplierOptions.find((item) => String(item.value) === row.supplierId)?.code ?? "—"}</span><span>{row.isPrimarySupplier ? "Yes" : "No"}</span><span><i className={row.isActive ? "status-dot" : "status-dot off"}/>{row.isActive ? "Active" : "Inactive"}</span><div><button className="btn btn-secondary btn-compact" onClick={() => openLink(index)}>Edit</button><button className="btn btn-secondary btn-compact" onClick={() => setLinks((items) => items.map((item, i) => i === index ? { ...item, isActive: !item.isActive, isPrimarySupplier: item.isActive ? false : item.isPrimarySupplier } : item))}>{row.isActive ? "Deactivate" : "Activate"}</button></div></div>)}</div><div className="supplier-panel-footer"><button className="btn btn-secondary" disabled={unitsDirty} onClick={() => openLink()}>＋ Add Supplier</button><button className="btn btn-primary" disabled={!linksDirty || unitsDirty || busy} onClick={() => void saveLinks()}>Save Supplier Changes</button></div></section>
    <section className="supplier-price-panel"><div className="panel-title-row"><h3>Supplier Purchase Units</h3><button className="btn btn-secondary" disabled={unitsDirty || linksDirty || !activeLinks.length} onClick={() => openUnit()}>＋ Add Unit</button></div><div className="supplier-price-table"><div className="supplier-price-row supplier-unit-columns supplier-price-table-head"><span>Supplier</span><span>Purchase Unit</span><span>Supplier Item Code</span><span>MOQ</span><span>Lead Time</span><span>Default</span><span>Status</span><span>Actions</span></div>{supplierUnits.map((row, index) => <div className="supplier-price-row supplier-unit-columns" key={row.productSupplierUnitId ?? `new-unit-${index}`}><strong>{supplierName(linkById(row.productSupplierId)?.supplierId ?? "")}</strong><strong>{unitName(row.productUnitId)}</strong><span>{row.supplierProductCode || "—"}</span><span>{row.minimumOrderQty || "—"}</span><span>{row.leadTimeDays ? `${row.leadTimeDays} days` : "—"}</span><span>{row.isDefaultPurchaseUnit ? "Yes" : "No"}</span><span><i className={row.isActive ? "status-dot" : "status-dot off"}/>{row.isActive ? "Active" : "Inactive"}</span><div><button className="btn btn-secondary btn-compact" onClick={() => openUnit(index)}>Edit</button><button className="btn btn-secondary btn-compact" onClick={() => toggleUnit(index)}>{row.isActive ? "Deactivate" : "Activate"}</button></div></div>)}</div><div className="supplier-panel-footer"><span/><button className="btn btn-primary" disabled={!supplierUnitsDirty || unitsDirty || linksDirty || busy} onClick={() => void saveSupplierUnits()}>Save Supplier Unit Changes</button></div></section>
    <section className="supplier-price-panel"><div className="panel-title-row"><h3>Purchase Prices</h3><button className="btn btn-secondary" disabled={blocked || !activeSupplierUnits.length} onClick={() => openPrice("ADD")}>＋ Add Purchase Price</button></div><div className="supplier-price-table"><div className="supplier-price-row supplier-purchase-columns supplier-price-table-head"><span>Supplier</span><span>Purchase Unit</span><span>Current Cost</span><span>Effective From</span><span>Effective End</span><span>Next Scheduled</span><span>Actions</span></div>{summary.map((group) => <div className="supplier-price-row supplier-purchase-columns" key={group.productSupplierUnitId}><strong>{group.supplier.supplierName}</strong><strong>{group.productUnit?.unit?.name ?? group.productUnit?.unit?.code}</strong><strong>{group.current ? money(group.current.currencyCode, group.current.purchasePrice) : "—"}</strong><span>{dateTime(group.current?.effectiveFrom)}</span><span>{dateTime(group.current?.effectiveTo)}</span><span>{group.nextScheduled ? <>{money(group.nextScheduled.currencyCode, group.nextScheduled.purchasePrice)} from {dateTime(group.nextScheduled.effectiveFrom)} <button className="link-button" onClick={() => cancelFuture(group)}>Cancel</button></> : "—"}</span><div>{group.current && <><button className="btn btn-secondary btn-compact" onClick={() => openPrice("CHANGE", group)}>Change Price</button><button className="btn btn-secondary btn-compact" onClick={() => openPrice("END", group)}>End Price</button></>}</div></div>)}</div></section>
    <section className="supplier-price-panel draft-panel"><h3>Draft Purchase Price Changes</h3><div className="supplier-price-table"><div className="supplier-price-row draft-price-columns supplier-price-table-head"><span>Supplier</span><span>Purchase Unit</span><span>Proposed Cost Change</span><span>Effective From</span><span>Actions</span></div>{drafts.map((row, index) => <div className="supplier-price-row draft-price-columns" key={row.id}><strong>{row.supplierLabel}</strong><strong>{row.unitLabel}</strong><span>{row.action === "CHANGE_PRICE" ? `${money(row.currencyCode, row.currentPrice ?? 0)} → ${money(row.currencyCode, row.price ?? 0)}` : row.action === "ADD_INITIAL_PRICE" ? `Add ${money(row.currencyCode, row.price ?? 0)}` : row.action === "END_PRICE" ? "End current price" : "Cancel scheduled price"}</span><span>{row.effectiveMode === "NOW" ? "On publish (server time)" : dateTime(row.effectiveFrom ?? row.effectiveTo)}</span><div>{row.action !== "CANCEL_FUTURE_PRICE" && <button className="btn btn-secondary btn-compact" onClick={() => editDraft(index)}>Edit</button>}<button className="btn btn-secondary btn-compact" onClick={() => setDrafts((items) => items.filter((_, i) => i !== index))}>Discard</button></div></div>)}</div></section>

    <Modal open={linkEditor !== null} title={linkEditor === "new" ? "Add Supplier" : "Edit Supplier"} onClose={() => setLinkEditor(null)}><div className="modal-body"><SearchableSelect label="Supplier" value={linkForm.supplierId} onChange={(value) => setLinkForm({ ...linkForm, supplierId: value })} options={supplierOptions} placeholder="Search suppliers..." emptyMessage="No suppliers found." required/><label className="check"><input type="checkbox" checked={linkForm.isPrimarySupplier} disabled={!linkForm.isActive} onChange={(event) => setLinkForm({ ...linkForm, isPrimarySupplier: event.target.checked })}/> Primary supplier</label></div><div className="modal-foot"><button className="btn btn-secondary" onClick={() => setLinkEditor(null)}>Cancel</button><button className="btn btn-primary" onClick={keepLink}>Keep Change</button></div></Modal>
    <Modal open={unitEditor !== null} title={unitEditor === "new" ? "Add Supplier Purchase Unit" : "Edit Supplier Purchase Unit"} onClose={() => setUnitEditor(null)}><div className="modal-body"><div className="form-grid"><Field label="Supplier" value={unitForm.productSupplierId} onChange={(value) => setUnitForm({ ...unitForm, productSupplierId: Number(value) })} options={activeLinks.map((row) => ({ value: row.productSupplierId!, label: supplierName(row.supplierId) }))} required disabled={unitEditor !== "new"}/><Field label="Purchase Unit" value={unitForm.productUnitId} onChange={(value) => setUnitForm({ ...unitForm, productUnitId: Number(value) })} options={purchaseUnits} required disabled={unitEditor !== "new"}/><Field label="Supplier Item Code" value={unitForm.supplierProductCode} onChange={(value) => setUnitForm({ ...unitForm, supplierProductCode: value })}/><Field label="MOQ" type="number" value={unitForm.minimumOrderQty} onChange={(value) => setUnitForm({ ...unitForm, minimumOrderQty: value })}/><Field label="Lead Time Days" type="number" value={unitForm.leadTimeDays} onChange={(value) => setUnitForm({ ...unitForm, leadTimeDays: value })}/><label className="check"><input type="checkbox" checked={unitForm.isDefaultPurchaseUnit} onChange={(event) => setUnitForm({ ...unitForm, isDefaultPurchaseUnit: event.target.checked })}/> Default purchase unit</label></div></div><div className="modal-foot"><button className="btn btn-secondary" onClick={() => setUnitEditor(null)}>Cancel</button><button className="btn btn-primary" onClick={keepUnit}>Keep Change</button></div></Modal>
    <Modal open={priceEditor !== null} title={`${priceEditor?.kind === "ADD" ? "Add" : priceEditor?.kind === "CHANGE" ? "Change" : "End"} Purchase Price`} onClose={() => setPriceEditor(null)}><div className="modal-body"><div className="form-grid"><Field label="Supplier" value={priceForm.supplierId} onChange={(value) => setPriceForm({ ...priceForm, supplierId: value, productSupplierUnitId: "" })} options={activeLinks.map((row) => ({ value: row.supplierId, label: supplierName(row.supplierId) }))} required disabled={priceEditor?.kind !== "ADD"}/><Field label="Purchase Unit" value={priceForm.productSupplierUnitId} onChange={(value) => setPriceForm({ ...priceForm, productSupplierUnitId: value })} options={activeSupplierUnits.filter((row) => linkById(row.productSupplierId)?.supplierId === priceForm.supplierId).map((row) => ({ value: row.productSupplierUnitId!, label: unitName(row.productUnitId) }))} required disabled={priceEditor?.kind !== "ADD"}/>{priceEditor?.kind !== "END" && <Field label="Purchase Price" type="number" value={priceForm.price} onChange={(value) => setPriceForm({ ...priceForm, price: value })} required/>}<Field label="Effective Time" value={priceForm.effectiveMode} onChange={(value) => setPriceForm({ ...priceForm, effectiveMode: value })} options={[{ value: "NOW", label: "Now (server time)" }, { value: "SCHEDULED", label: "Scheduled" }]}/>{priceForm.effectiveMode === "SCHEDULED" && <Field label={priceEditor?.kind === "END" ? "Effective End" : "Effective From"} type="datetime-local" value={priceEditor?.kind === "END" ? priceForm.effectiveTo : priceForm.effectiveFrom} onChange={(value) => setPriceForm(priceEditor?.kind === "END" ? { ...priceForm, effectiveTo: value } : { ...priceForm, effectiveFrom: value })} required/>}</div></div><div className="modal-foot"><button className="btn btn-secondary" onClick={() => setPriceEditor(null)}>Cancel</button><button className="btn btn-primary" onClick={saveDraft}>Add to Drafts</button></div></Modal>
    <Modal open={publishOpen} title="Publish Purchase Prices" subtitle="All draft actions will be validated and saved atomically." onClose={() => setPublishOpen(false)}><div className="modal-body"><p>Publish {drafts.length} purchase-price change{drafts.length === 1 ? "" : "s"}? If one action is invalid, none will be saved.</p></div><div className="modal-foot"><button className="btn btn-secondary" onClick={() => setPublishOpen(false)}>Cancel</button><button className="btn btn-primary" disabled={busy} onClick={() => void publish()}>Publish Purchase Prices</button></div></Modal>
    <Modal open={historyOpen} title="Purchase Price History" onClose={() => setHistoryOpen(false)} wide><div className="modal-body"><div className="history-filters"><Field label="Supplier" value={filters.supplierId} onChange={(value) => setFilters({ ...filters, page: 1, supplierId: value })} options={supplierOptions}/><Field label="Supplier Purchase Unit" value={filters.productSupplierUnitId} onChange={(value) => setFilters({ ...filters, page: 1, productSupplierUnitId: value })} options={supplierUnits.map((row) => ({ value: row.productSupplierUnitId!, label: `${supplierName(linkById(row.productSupplierId)?.supplierId ?? "")} · ${unitName(row.productUnitId)}` }))}/><Field label="Status" value={filters.status} onChange={(value) => setFilters({ ...filters, page: 1, status: value })} options={[{ value: "CURRENT", label: "Current" }, { value: "FUTURE", label: "Future" }, { value: "ENDED", label: "Ended" }]}/><Field label="From" type="date" value={filters.fromDate} onChange={(value) => setFilters({ ...filters, page: 1, fromDate: value })}/><Field label="To" type="date" value={filters.toDate} onChange={(value) => setFilters({ ...filters, page: 1, toDate: value })}/></div><div className="supplier-price-table"><div className="supplier-price-row history-price-columns supplier-price-table-head"><span>Supplier</span><span>Purchase Unit</span><span>Cost</span><span>Effective Period</span><span>Status</span></div>{history?.items.map((row: any) => <div className="supplier-price-row history-price-columns" key={row.productSupplierPriceId}><strong>{row.supplier?.supplierName}</strong><span>{row.productUnit?.unit?.name ?? row.productUnit?.unit?.code}</span><strong>{money(row.currencyCode, row.purchasePrice)}</strong><span>{dateTime(row.effectiveFrom)} – {dateTime(row.effectiveTo)}</span><span>{row.status}</span></div>)}</div></div><div className="modal-foot"><button className="btn btn-secondary" disabled={!history || history.page <= 1} onClick={() => setFilters({ ...filters, page: filters.page - 1 })}>Previous</button><span>Page {history?.page ?? 1} of {history?.totalPages ?? 1}</span><button className="btn btn-secondary" disabled={!history || history.page >= history.totalPages} onClick={() => setFilters({ ...filters, page: filters.page + 1 })}>Next</button></div></Modal>
  </div>;
}
