import { useMemo, useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { tenantsApi } from '../api/tenantsApi';
import { Modal } from '../../../components/ui/Modal';
import { Field } from '../../../components/ui/Field';

type Form = { tenantCode: string; tenantName: string };
const idOf = (row: any) => Number(row.tenantId ?? row.id);
const nameOf = (row: any) => row.tenantName ?? row.name ?? '';
const codeOf = (row: any) => row.tenantCode ?? row.code ?? '';

export function TenantsPage() {
  const queryClient = useQueryClient();
  const tenants = useQuery({ queryKey: ['tenants'], queryFn: tenantsApi.list });
  const [open, setOpen] = useState(false); const [editing, setEditing] = useState<any>(null); const [modulesTenant, setModulesTenant] = useState<any>(null); const [search, setSearch] = useState('');
  const [form, setForm] = useState<Form>({ tenantCode: '', tenantName: '' });
  const save = useMutation({ mutationFn: (data: Form) => editing ? tenantsApi.update(idOf(editing), data) : tenantsApi.create(data), onSuccess: () => { queryClient.invalidateQueries({ queryKey: ['tenants'] }); setOpen(false); setEditing(null); } });
  const deactivate = useMutation({ mutationFn: (id: number) => tenantsApi.deactivate(id), onSuccess: () => queryClient.invalidateQueries({ queryKey: ['tenants'] }) });
  const activate = useMutation({ mutationFn: (id: number) => tenantsApi.activate(id), onSuccess: () => queryClient.invalidateQueries({ queryKey: ['tenants'] }) });
  const rows = useMemo(() => (tenants.data ?? []).filter((row: any) => `${codeOf(row)} ${nameOf(row)}`.toLowerCase().includes(search.toLowerCase())), [tenants.data, search]);
  const edit = (tenant: any) => { setEditing(tenant); setForm({ tenantCode: codeOf(tenant), tenantName: nameOf(tenant) }); setOpen(true); };
  return <div><div className="page-head"><div><div className="eyebrow">SYSTEM ADMINISTRATION</div><h1>Tenants</h1><p>Manage independent businesses and their ERP environments.</p></div><button className="btn btn-primary" onClick={() => { setEditing(null); setForm({ tenantCode: '', tenantName: '' }); setOpen(true); }}>＋ New tenant</button></div>
    <div className="stats-row"><div className="stat-card"><span>Total tenants</span><strong>{tenants.data?.length ?? 0}</strong></div><div className="stat-card"><span>Active</span><strong>{(tenants.data ?? []).filter((row: any) => row.tenantIsActive ?? row.isActive ?? true).length}</strong></div><div className="stat-card"><span>Inactive</span><strong>{(tenants.data ?? []).filter((row: any) => (row.tenantIsActive ?? row.isActive) === false).length}</strong></div></div>
    <div className="card"><div className="toolbar"><div className="search-wrap"><span>⌕</span><input className="input search" placeholder="Search by tenant name or code..." value={search} onChange={event => setSearch(event.target.value)} /></div><button className="btn btn-secondary" onClick={() => tenants.refetch()}>↻ Refresh</button></div>{tenants.isLoading ? <div className="empty">Loading tenants...</div> : rows.length === 0 ? <div className="empty">No tenants found.</div> : <table className="table"><thead><tr><th>Tenant</th><th>Code</th><th>Status</th><th>Created</th><th className="right">Actions</th></tr></thead><tbody>{rows.map((tenant: any) => { const active = tenant.tenantIsActive ?? tenant.isActive ?? true; return <tr key={idOf(tenant)}><td><div className="primary-cell"><span className="avatar tenant-avatar">{nameOf(tenant).slice(0, 1).toUpperCase()}</span><div><strong>{nameOf(tenant)}</strong><small>Tenant #{idOf(tenant)}</small></div></div></td><td><span className="code-chip">{codeOf(tenant)}</span></td><td><span className={active ? 'status status-on' : 'status status-off'}><i /> {active ? 'Active' : 'Inactive'}</span></td><td>{tenant.createdAt ? new Date(tenant.createdAt).toLocaleDateString() : '—'}</td><td className="right actions"><button className="btn btn-ghost" onClick={() => edit(tenant)}>Edit</button><button className="btn btn-ghost" onClick={() => setModulesTenant(tenant)}>Manage Modules</button>{active ? <button className="btn btn-danger-soft" onClick={() => deactivate.mutate(idOf(tenant))}>Deactivate</button> : <button className="btn btn-primary" onClick={() => activate.mutate(idOf(tenant))}>Activate</button>}</td></tr>; })}</tbody></table>}</div>
    <Modal open={open} onClose={() => setOpen(false)} title={editing ? 'Edit tenant' : 'Create tenant'} subtitle="Tenant identity and lifecycle settings."><form onSubmit={event => { event.preventDefault(); save.mutate(form); }}><div className="modal-body"><div className="form-grid"><Field label="Tenant code" value={form.tenantCode} onChange={value => setForm({ ...form, tenantCode: value.toUpperCase() })} required /><Field label="Tenant name" value={form.tenantName} onChange={value => setForm({ ...form, tenantName: value })} required full /></div>{save.error && <div className="error-box">{(save.error as Error).message}</div>}</div><div className="modal-foot"><button type="button" className="btn btn-secondary" onClick={() => setOpen(false)}>Cancel</button><button className="btn btn-primary" disabled={save.isPending}>{save.isPending ? 'Saving...' : 'Save'}</button></div></form></Modal>
    <TenantModulesModal tenant={modulesTenant} onClose={() => setModulesTenant(null)} />
  </div>;
}

function TenantModulesModal({ tenant, onClose }: { tenant: any; onClose: () => void }) {
  const queryClient = useQueryClient(); const tenantId = tenant ? idOf(tenant) : 0;
  const modules = useQuery({ queryKey: ['tenant-modules', tenantId], queryFn: () => tenantsApi.listModules(tenantId), enabled: Boolean(tenant) });
  const update = useMutation({ mutationFn: ({ moduleId, isEnabled }: { moduleId: number; isEnabled: boolean }) => tenantsApi.setModuleEnabled(tenantId, moduleId, isEnabled), onSuccess: () => queryClient.invalidateQueries({ queryKey: ['tenant-modules', tenantId] }) });
  return <Modal open={Boolean(tenant)} onClose={onClose} title="Manage Modules" subtitle={tenant ? `Tenant: ${codeOf(tenant)} · ${nameOf(tenant)}` : undefined} wide><div className="modal-body"><div className="context-banner"><span>•</span><div><strong>Platform-controlled modules</strong><small>Disabled modules disappear for tenant users and are blocked by backend authorization.</small></div></div><div className="card" style={{ marginTop: 12 }}>{modules.isLoading ? <div className="empty">Loading modules...</div> : (modules.data ?? []).map((module: any) => <div key={module.moduleId} style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', padding: '12px 16px', borderBottom: '1px solid #e5e7eb' }}><div><strong>{module.name}</strong><small style={{ display: 'block' }}>{module.code}</small></div><label className="check"><input type="checkbox" checked={module.isEnabled} disabled={update.isPending} onChange={event => update.mutate({ moduleId: Number(module.moduleId), isEnabled: event.target.checked })} /> {module.isEnabled ? 'Enabled' : 'Disabled'}</label></div>)}</div>{update.error && <div className="error-box">{(update.error as Error).message}</div>}</div><div className="modal-foot"><button className="btn btn-secondary" onClick={onClose}>Close</button></div></Modal>;
}
