import { createContext, useCallback, useContext, useEffect, useMemo, useState } from 'react';
import type { ReactNode } from 'react';
import { platformLogin, tenantLogin } from './authApi';
import { AUTH_STATE_KEY, AUTH_TOKEN_KEY, AUTH_UNAUTHORIZED_EVENT } from './auth.types';
import type { AuthState } from './auth.types';
const emptyState: AuthState = { accessToken:null, scope:null, platformUser:null, tenant:null, tenantUser:null, roles:[], role:null, accessScope:null, assignedLocations:[], modules:[], permissions:[], currentLocationId:null, expiresAt:null };
function readStoredState(): AuthState { try { const raw=localStorage.getItem(AUTH_STATE_KEY); if(!raw) return emptyState; const parsed=JSON.parse(raw) as Partial<AuthState>; const state={...emptyState,...parsed,roles:parsed.roles??[],assignedLocations:parsed.assignedLocations??[],modules:parsed.modules??[],permissions:parsed.permissions??[]}; if(state.accessScope==='LOCATION' && !state.currentLocationId) state.currentLocationId=state.assignedLocations.find(x=>x.isDefault)?.locationId??state.assignedLocations[0]?.locationId??null; if(state.expiresAt && new Date(state.expiresAt).getTime()<=Date.now()){localStorage.removeItem(AUTH_STATE_KEY);localStorage.removeItem(AUTH_TOKEN_KEY);return emptyState;} return state;} catch {localStorage.removeItem(AUTH_STATE_KEY);localStorage.removeItem(AUTH_TOKEN_KEY);return emptyState;} }
type AuthContextValue = AuthState & { isAuthenticated:boolean; loginAsPlatform:(u:string,p:string)=>Promise<void>; loginAsTenant:(t:string,u:string,p:string)=>Promise<void>; setCurrentLocation:(id:string)=>void; logout:()=>void; };
const AuthContext=createContext<AuthContextValue|undefined>(undefined);
export function AuthProvider({children}:{children:ReactNode}) { const [state,setState]=useState<AuthState>(readStoredState); const save=useCallback((next:AuthState)=>{localStorage.setItem(AUTH_TOKEN_KEY,next.accessToken??'');localStorage.setItem(AUTH_STATE_KEY,JSON.stringify(next));setState(next);},[]); const logout=useCallback(()=>{localStorage.removeItem(AUTH_STATE_KEY);localStorage.removeItem(AUTH_TOKEN_KEY);setState(emptyState);},[]); const loginAsPlatform=useCallback(async(u:string,p:string)=>{const r=await platformLogin({username:u,password:p});save({...emptyState,accessToken:r.accessToken,scope:r.scope,platformUser:r.platformUser,expiresAt:r.expiresAt});},[save]); const loginAsTenant=useCallback(async(t:string,u:string,p:string)=>{const r=await tenantLogin({tenantCode:t,username:u,password:p});const currentLocationId=r.accessScope==='LOCATION'?(r.assignedLocations.find(x=>x.isDefault)?.locationId??r.assignedLocations[0]?.locationId??null):null;save({...emptyState,accessToken:r.accessToken,scope:r.scope,tenant:r.tenant,tenantUser:r.user,roles:r.roles,role:r.role,accessScope:r.accessScope,assignedLocations:r.assignedLocations,modules:r.modules,permissions:r.permissions,currentLocationId,expiresAt:r.expiresAt});},[save]); const setCurrentLocation=useCallback((currentLocationId:string)=>{if(!state.assignedLocations.some(location=>location.locationId===currentLocationId))return;save({...state,currentLocationId});},[save,state]); useEffect(()=>{const h=()=>logout();window.addEventListener(AUTH_UNAUTHORIZED_EVENT,h);return()=>window.removeEventListener(AUTH_UNAUTHORIZED_EVENT,h);},[logout]); useEffect(()=>{if(!state.expiresAt)return;const ms=new Date(state.expiresAt).getTime()-Date.now();if(ms<=0){logout();return;}const timer=window.setTimeout(logout,ms);return()=>window.clearTimeout(timer);},[state.expiresAt,logout]); const value=useMemo(()=>({...state,isAuthenticated:Boolean(state.accessToken&&state.scope),loginAsPlatform,loginAsTenant,setCurrentLocation,logout}),[state,loginAsPlatform,loginAsTenant,setCurrentLocation,logout]); return <AuthContext.Provider value={value}>{children}</AuthContext.Provider>; }
export function useAuth(){const value=useContext(AuthContext);if(!value)throw new Error('useAuth must be used inside AuthProvider');return value;}
