import { useMemo, useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { usersApi } from '../api/usersApi';
import { rolesApi } from '../../roles/api/rolesApi';
import { Modal } from '../../../components/ui/Modal';
import { Field } from '../../../components/ui/Field';

const idOf=(r:any)=>r.userId ?? r.id;
const roleIdOf=(r:any)=>r.roleId ?? r.id;
export function UsersPage(){
 const qc=useQueryClient(); const q=useQuery({queryKey:['users'],queryFn:usersApi.list}); const roles=useQuery({queryKey:['roles'],queryFn:rolesApi.list});
 const [open,setOpen]=useState(false),[editing,setEditing]=useState<any>(null),[search,setSearch]=useState('');
 const [form,setForm]=useState<any>({username:'',email:'',password:'',firstName:'',lastName:'',mobile:'',roleId:''});
 const save=useMutation({mutationFn:(data:any)=>editing?usersApi.update(idOf(editing),data):usersApi.create(data),onSuccess:()=>{qc.invalidateQueries({queryKey:['users']});setOpen(false);setEditing(null)}});
 const deactivate=useMutation({mutationFn:(id:number)=>usersApi.deactivate(id),onSuccess:()=>qc.invalidateQueries({queryKey:['users']})});
 const rows=useMemo(()=> (q.data??[]).filter(r=>`${r.username??''} ${r.email??''} ${r.firstName??''} ${r.lastName??''}`.toLowerCase().includes(search.toLowerCase())),[q.data,search]);
 const edit=(r:any)=>{setEditing(r);setForm({username:r.username??'',email:r.email??'',password:'',firstName:r.firstName??'',lastName:r.lastName??'',mobile:r.mobile??'',roleId:r.userRoles?.[0]?.roleId ?? r.userRoles?.[0]?.role?.roleId ?? ''});setOpen(true)};
 const roleOptions=(roles.data??[]).filter((r:any)=>r.isActive!==false).map((r:any)=>({value:roleIdOf(r),label:`${r.name??r.roleName??r.code} (${r.code??''})`}));
 return <div><div className="page-head"><div><div className="eyebrow">ACCESS MANAGEMENT</div><h1>Users</h1><p>Create users inside the current tenant and assign their role.</p></div><button className="btn btn-primary" onClick={()=>{setEditing(null);setForm({username:'',email:'',password:'',firstName:'',lastName:'',mobile:'',roleId:''});setOpen(true)}}>＋ New user</button></div>
 <div className="card"><div className="toolbar"><div className="search-wrap"><span>⌕</span><input className="input search" placeholder="Search users..." value={search} onChange={e=>setSearch(e.target.value)}/></div></div><table className="table"><thead><tr><th>User</th><th>Email</th><th>Role</th><th>Status</th><th className="right">Actions</th></tr></thead><tbody>{q.isLoading?<tr><td colSpan={5}>Loading...</td></tr>:rows.map(r=>{const active=r.isActive!==false; const role=r.userRoles?.[0]?.role?.name ?? r.userRoles?.[0]?.role?.code ?? '—'; return <tr key={idOf(r)}><td><div className="primary-cell"><span className="avatar user-avatar">{`${r.firstName??''} ${r.lastName??''}`.trim().slice(0,1).toUpperCase()||r.username?.slice(0,1).toUpperCase()}</span><div><strong>{`${r.firstName??''} ${r.lastName??''}`.trim()||r.username}</strong><small>@{r.username}</small></div></div></td><td>{r.email??'—'}</td><td><span className="role-chip">{role}</span></td><td><span className={active?'status status-on':'status status-off'}><i/> {active?'Active':'Inactive'}</span></td><td className="right actions"><button className="btn btn-ghost" onClick={()=>edit(r)}>Edit</button>{active&&<button className="btn btn-danger-soft" onClick={()=>deactivate.mutate(idOf(r))}>Deactivate</button>}</td></tr>})}</tbody></table></div>
 <Modal open={open} onClose={()=>setOpen(false)} title={editing?'Edit user':'Create user'} subtitle="Tenant is inherited from the authenticated user; it is not selected here." wide><form onSubmit={e=>{e.preventDefault();const payload={username:form.username,email:form.email,password:form.password||undefined,firstName:form.firstName,lastName:form.lastName,mobile:form.mobile,roleIds:form.roleId?[Number(form.roleId)]:[]};save.mutate(payload)}}><div className="modal-body"><div className="context-banner"><span>✓</span><div><strong>Current tenant context</strong><small>Users created here belong to the tenant in the signed-in account.</small></div></div><div className="form-grid"><Field label="Username" value={form.username} onChange={v=>setForm({...form,username:v})} required/><Field label="Role" value={form.roleId} onChange={v=>setForm({...form,roleId:v})} options={roleOptions} required/><Field label="First name" value={form.firstName} onChange={v=>setForm({...form,firstName:v})}/><Field label="Last name" value={form.lastName} onChange={v=>setForm({...form,lastName:v})}/><Field label="Email" value={form.email} onChange={v=>setForm({...form,email:v})} type="email"/><Field label="Mobile" value={form.mobile} onChange={v=>setForm({...form,mobile:v})}/>{!editing&&<Field label="Temporary password" value={form.password} onChange={v=>setForm({...form,password:v})} type="password" required hint="User can change this after first sign-in."/>}</div>{save.error&&<div className="error-box">{(save.error as Error).message}</div>}</div><div className="modal-foot"><button type="button" className="btn btn-secondary" onClick={()=>setOpen(false)}>Cancel</button><button className="btn btn-primary" disabled={save.isPending}>{save.isPending?'Saving...':editing?'Save changes':'Create user'}</button></div></form></Modal>
 </div>
}
