export const LABELS: Record<string, string> = {
  reportDate: "Date", location: "Location", invoice: "Invoice", cashier: "Cashier",
  customer: "Customer", category: "Category", sku: "SKU", product: "Product Name",
  categoryLevel1: "Category Level 1", categoryLevel2: "Category Level 2", categoryLevel3: "Category Level 3",
  refundQty: "Refund Qty", netSalesBeforeRefund: "Sales Net Before Refund",
  cogsMissing: "Missing Cost Records",
  qty: "Qty", grossSales: "Gross Sales", discount: "Sales Discount", netSales: "Actual Net Sales",
  cogs: "COGS", gp: "GP", gpPercent: "GP %", refundValue: "Refund Value",
  netQty: "Net Qty", billCount: "Bill Count", primarySupplier: "Primary Supplier",
  paymentMethod: "Payment Method", channel: "Channel", paymentValue: "Payment",
  unitCost: "Unit Cost", stockValue: "Stock Value", lastMovementAt: "Last Movement", brand: "Brand",
  movementType: "Movement Type", sourceDocumentType: "Source Type",
  sourceDocumentId: "Source Document", sourceDocumentLineId: "Source Line",
  qtyIn: "Qty In", qtyOut: "Qty Out", qtyBefore: "Qty Before", qtyAfter: "Qty After",
  receiptDate: "Receipt Date", ageDays: "Age (Days)", agingBucket: "Aging Bucket", batch: "Batch",
  expiryDate: "Expiry Date", purchaseOrder: "Purchase Order", status: "Status",
  receivedQty: "Received Qty", lineValue: "Line Value", grn: "GRN",
  refund: "Refund", originalInvoice: "Original Invoice", reason: "Reason",
  register: "Register", terminal: "Terminal", eventType: "Record Type",
  ageLayerId: "Aging Layer ID", sessionId: "Session ID", amount: "Amount", openingBalance: "Opening Balance",
  expectedCash: "Expected Cash", countedCash: "Counted Cash", variance: "Variance",
  reconciliationStatus: "Reconciliation Status", openedAt: "Opened At",
  closedAt: "Closed At", openedBy: "Opened By", closedBy: "Closed By",
  cashierSessionCount: "Cashier Sessions", cashMovementValue: "Cash Movements",
  periodKey: "Period", weekYear: "Week Year", weekNumber: "Week Number", weekLabel: "ISO Week",
  weekStartDate: "Week Start", weekEndDate: "Week End", year: "Year", monthNumber: "Month", monthName: "Month Name",
  saleCogs: "Sale COGS", cogsReversal: "COGS Reversal",
  paymentCount: "Payments", paymentMethodType: "Method Type", channelCode: "Channel Code", externalReference: "External Reference",
  incomingTransitQty: "Incoming Transit Qty", incomingTransitValue: "Incoming Transit Value",
  outgoingTransitQty: "Outgoing Transit Qty", outgoingTransitValue: "Outgoing Transit Value",
  companyOwnedValue: "Company-Owned Value", openPoBaseQty: "Open PO Base Qty", incomingTransferQty: "Incoming Transfer Qty",
  inventoryPositionQty: "Inventory Position Qty", consumptionQty: "Consumption Qty", perDayRate: "Per-Day Rate",
  rateFrom: "Rate From", rateTo: "Rate To", rateHorizonDays: "Rate Horizon Days", leadTimeDays: "Lead Time Days", leadTimeSource: "Lead Time Source",
  leadTimeDemand: "Lead-Time Demand", daysOfSupply: "Days of Supply", weeksOfSupply: "Weeks of Supply",
  targetCoverageDays: "Target Coverage Days", targetStock: "Target Stock", reorderStatus: "Reorder Status", suggestedBaseQty: "Suggested Base Qty",
  suggestedPurchaseUnit: "Suggested Purchase Unit", suggestedPurchaseQty: "Suggested Purchase Qty",
  suggestedConvertedBaseQty: "Suggested Converted Base Qty", qty0to30: "0–30 Days", qty31to60: "31–60 Days",
  qty61to90: "61–90 Days", qty91to180: "91–180 Days", qty181to365: "181–365 Days", qty365plus: "366+ Days",
  unknownQty: "Unknown Qty", attributedQty: "Attributed Qty", agingCoveragePercentage: "Coverage %",
  averageAgeDays: "Average Age Days", oldestAgeDays: "Oldest Age Days",
};

