import { useEffect, useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { posRegistersApi } from '../api/posRegistersApi';
import { posPrintApi, PrintProfile } from '../api/posPrintApi';
import { env } from '../../../config/env';
import { buildAgentConfig } from './agentConfig';

const empty = (locationId: number): Omit<PrintProfile, 'posPrintProfileId'> => ({ locationId, posTerminalId: null, displayName: 'Receipt printer', transport: 'TCP', target: '', port: 9100, paperWidth: 80, encoding: 'CP437', cutEnabled: true, isActive: true });

const agentConfig = (profileId: number, token: string) => buildAgentConfig(env.apiUrl, window.location.origin, profileId, token);

export function PosPrinterSettings({ locationId }: { locationId: number }) {
  const client = useQueryClient();
  const [terminalId, setTerminalId] = useState<number | null>(null);
  const [form, setForm] = useState(empty(locationId));
  const [generated, setGenerated] = useState<{ profileId: number; token: string } | null>(null);
  const [queuePage, setQueuePage] = useState(1);
  const [message, setMessage] = useState('');
  const profiles = useQuery({ queryKey: ['pos-print-profiles', locationId], queryFn: () => posPrintApi.profiles(locationId), enabled: locationId > 0 });
  const receiptReadiness = useQuery({ queryKey: ['pos-receipt-readiness', locationId], queryFn: () => posPrintApi.receiptReadiness(locationId), enabled: locationId > 0 });
  const terminals = useQuery({ queryKey: ['pos-print-terminals', locationId], queryFn: () => posRegistersApi.terminals({ locationId, limit: 100 }), enabled: locationId > 0 });
  const selected = profiles.data?.find((profile) => Number(profile.posTerminalId ?? 0) === Number(terminalId ?? 0));
  const terminal = (terminals.data?.items ?? []).find((item) => Number(item.posTerminalId) === terminalId);
  const terminalLabel = terminal ? `${terminal.terminalCode} · ${terminal.displayName}` : String(terminalId ?? '');
  const jobs = useQuery({ queryKey: ['pos-print-jobs', locationId, selected?.posPrintProfileId, queuePage], queryFn: () => posPrintApi.jobs(locationId, queuePage, selected?.posPrintProfileId), enabled: locationId > 0, refetchInterval: 10000 });
  useEffect(() => { if (jobs.data && queuePage > Math.max(1, Math.ceil(jobs.data.total / 20))) setQueuePage(Math.max(1, Math.ceil(jobs.data.total / 20))); }, [jobs.data?.total, queuePage]);
  useEffect(() => { setGenerated(null); setQueuePage(1); }, [locationId, terminalId]);
  useEffect(() => { setForm(selected ? { ...selected, locationId, posTerminalId: terminalId } : { ...empty(locationId), posTerminalId: terminalId }); }, [locationId, terminalId, selected?.posPrintProfileId, profiles.dataUpdatedAt]);
  const refresh = () => { void client.invalidateQueries({ queryKey: ['pos-print-profiles', locationId] }); void client.invalidateQueries({ queryKey: ['pos-print-jobs', locationId] }); };
  const save = useMutation({ mutationFn: () => posPrintApi.configure(form), onSuccess: (result) => { if (result.agentToken) setGenerated({ profileId: Number(result.profile.posPrintProfileId), token: result.agentToken }); setMessage(`Printer profile ${result.profile.posPrintProfileId} saved.`); refresh(); } });
  const test = useMutation({ mutationFn: () => posPrintApi.test(selected!.posPrintProfileId), onSuccess: (job) => { setMessage(`Test print queued as job ${job.posPrintJobId}.`); refresh(); } });
  const rotate = useMutation({ mutationFn: () => posPrintApi.rotateToken(selected!.posPrintProfileId), onSuccess: (result) => { setGenerated({ profileId: Number(result.profile.posPrintProfileId), token: result.agentToken }); setMessage('Agent credential rotated. Update the workstation configuration; the previous credential is invalid.'); } });
  const retry = useMutation({ mutationFn: (id: number) => posPrintApi.retry(id), onSuccess: refresh });
  if (!locationId) return null;
  return <section className="card"><div className="sales-card-head"><div><h2>Receipt printer</h2><p>Configure the local print agent for this location or one terminal. Cashier Print sends sale and refund receipts to this agent.</p></div></div>
    {receiptReadiness.data && <div className={receiptReadiness.data.warnings.length ? 'error-box' : 'success-box'}><strong>Receipt header: {receiptReadiness.data.companyName} / {receiptReadiness.data.locationName}</strong><p>{receiptReadiness.data.address.join(', ') || receiptReadiness.data.warnings.join(' ')}</p></div>}
<div className="success-box"><strong>{terminalId === null ? 'Location default assignment' : `Terminal assignment: ${terminalLabel}`}</strong><p>Agent Profile ID (pos_print_profile_id): <b>{selected?.posPrintProfileId ?? generated?.profileId ?? 'Save this assignment to create a profile'}</b>. Active terminal profiles receive their terminal's jobs first; otherwise the location default receives them.</p>{selected && <p>{selected.displayName} · {selected.transport} · {selected.target}{selected.port ? `:${selected.port}` : ''} · {selected.paperWidth} mm · {selected.encoding} · Cut {selected.cutEnabled ? 'on' : 'off'} · {selected.isActive ? 'Active' : 'Inactive'} · Agent credential exists</p>}</div>
    <div className="toolbar"><label className="field"><span>Assignment</span><select className="control" value={terminalId ?? ''} onChange={(event) => setTerminalId(event.target.value ? Number(event.target.value) : null)}><option value="">Location default</option>{(terminals.data?.items ?? []).map((terminal) => <option key={terminal.posTerminalId} value={terminal.posTerminalId}>{terminal.terminalCode} · {terminal.displayName}</option>)}</select></label>
      <label className="field"><span>Display name</span><input className="control" value={form.displayName} onChange={(event) => setForm({ ...form, displayName: event.target.value })}/></label>
      <label className="field"><span>Connection</span><select className="control" value={form.transport} onChange={(event) => setForm({ ...form, transport: event.target.value as PrintProfile['transport'], target: '', port: event.target.value === 'TCP' ? 9100 : null })}><option value="TCP">Wi-Fi / Ethernet ESC/POS TCP</option><option value="WINDOWS_QUEUE">Windows USB/OS printer queue</option></select></label>
      <label className="field"><span>{form.transport === 'TCP' ? 'Private printer IP' : 'Windows queue name'}</span><input className="control" value={form.target} onChange={(event) => setForm({ ...form, target: event.target.value })} placeholder={form.transport === 'TCP' ? '192.168.1.50' : 'EPSON TM-T20'}/></label>
      {form.transport === 'TCP' && <label className="field"><span>TCP port</span><input className="control" type="number" min="1" max="65535" value={form.port ?? 9100} onChange={(event) => setForm({ ...form, port: Number(event.target.value) })}/></label>}
      <label className="field"><span>Paper width</span><select className="control" value={form.paperWidth} onChange={(event) => setForm({ ...form, paperWidth: Number(event.target.value) as 58 | 80 })}><option value="58">58 mm</option><option value="80">80 mm</option></select></label>
      <label className="field"><span>Encoding</span><select className="control" value={form.encoding} onChange={(event) => setForm({ ...form, encoding: event.target.value as PrintProfile['encoding'] })}><option value="CP437">CP437</option><option value="CP850">CP850</option><option value="UTF8">UTF-8 (supported printers only)</option></select></label>
      <label className="check"><input type="checkbox" checked={form.cutEnabled} onChange={(event) => setForm({ ...form, cutEnabled: event.target.checked })}/> Cut paper</label>
      <label className="check"><input type="checkbox" checked={form.isActive} onChange={(event) => setForm({ ...form, isActive: event.target.checked })}/> Active</label>
      <button className="btn btn-primary" disabled={save.isPending} onClick={() => save.mutate()}>Save printer</button>
      <button className="btn btn-secondary" disabled={!selected || test.isPending} onClick={() => test.mutate()}>{selected ? `Test print · profile ${selected.posPrintProfileId}` : "Test print"}</button>
      <button className="btn btn-secondary" disabled={!selected || rotate.isPending} onClick={() => rotate.mutate()}>Rotate agent credential</button>
    </div>
    {generated && <div className="success-box"><strong>Agent credential for profile {generated.profileId}</strong><p>Shown once. Store this configuration in the workstation's agent-config.json. The credential is reused on each poll until rotated. Keep it private.</p><div className="toolbar"><button className="btn btn-secondary" onClick={async () => { try { await navigator.clipboard.writeText(agentConfig(generated.profileId, generated.token)); setMessage('Agent config copied.'); } catch { setMessage('Clipboard unavailable. Use Download agent-config.json.'); } }}>Copy Agent Config</button><button className="btn btn-secondary" onClick={() => { const url = URL.createObjectURL(new Blob([agentConfig(generated.profileId, generated.token)], { type: 'application/json' })); const link = document.createElement('a'); link.href = url; link.download = 'agent-config.json'; link.click(); setTimeout(() => URL.revokeObjectURL(url), 1000); }}>Download agent-config.json</button></div></div>}
    {message && <div className="success-box">{message}</div>}{(profiles.error || jobs.error || save.error || test.error || rotate.error || retry.error) && <div className="error-box">{profiles.error?.message ?? jobs.error?.message ?? save.error?.message ?? test.error?.message ?? rotate.error?.message ?? retry.error?.message}</div>}
<h3>Actionable print queue</h3><p>Pending, claimed and failed jobs for {selected ? `profile ${selected.posPrintProfileId}` : 'this location'}. Old pending jobs remain queued until this profile is active and its agent claims them. Check the physical printer before retrying a failed job.</p><div className="table-scroll"><table className="table"><thead><tr><th>Job</th><th>Document</th><th>Profile / assignment</th><th>Status</th><th>Created / age</th><th>Attempts</th><th>Error</th><th></th></tr></thead><tbody>{(jobs.data?.items ?? []).map((job) => <tr key={job.posPrintJobId}><td>{job.posPrintJobId}</td><td>{job.documentType}{job.sourceId ? ` #${job.sourceId}` : ''}</td><td>#{job.posPrintProfileId} · {profiles.data?.find((profile) => Number(profile.posPrintProfileId) === Number(job.posPrintProfileId))?.posTerminalId ? `Terminal ${profiles.data?.find((profile) => Number(profile.posPrintProfileId) === Number(job.posPrintProfileId))?.posTerminalId}` : 'Location default'}</td><td>{job.status}</td><td>{new Date(job.createdAt).toLocaleString()}<br/><small>{Math.max(0, Math.floor((Date.now() - new Date(job.createdAt).getTime()) / 60000))} min ago</small></td><td>{job.attempts}</td><td>{job.lastError ?? '—'}</td><td>{job.status === 'FAILED' && <button className="btn btn-secondary" disabled={retry.isPending} onClick={() => retry.mutate(job.posPrintJobId)}>Retry</button>}</td></tr>)}{!jobs.isLoading && !jobs.data?.items.length && <tr><td colSpan={8}>No actionable jobs.</td></tr>}</tbody></table></div><div className="toolbar"><span>{jobs.data?.total ?? 0} actionable jobs · Page {queuePage}</span><button className="btn btn-secondary" disabled={queuePage <= 1} onClick={() => setQueuePage(queuePage - 1)}>Previous</button><button className="btn btn-secondary" disabled={queuePage * 20 >= (jobs.data?.total ?? 0)} onClick={() => setQueuePage(queuePage + 1)}>Next</button></div>
  </section>;
}
